#!/bin/bash

gsettings set org.gnome.DejaDup last-restore "''"
gsettings set org.gnome.DejaDup last-restore "''"
gsettings set org.gnome.DejaDup periodic "true"
gsettings set org.gnome.DejaDup periodic-period "1"
gsettings set org.gnome.DejaDup full-backup-period "90"
gsettings set org.gnome.DejaDup backend "'remote'"
gsettings set org.gnome.DejaDup last-run "'2020-07-08T17:16:03.270477Z'"
gsettings set org.gnome.DejaDup nag-check "'2020-07-08T17:16:03.275992Z'"
gsettings set org.gnome.DejaDup prompt-check "'2020-06-29T09:17:18.159531Z'"
gsettings set org.gnome.DejaDup root-prompt "true"
gsettings set org.gnome.DejaDup include-list "['/home/user']"
gsettings set org.gnome.DejaDup exclude-list "['/home/user/.local/share/Trash']"
gsettings set org.gnome.DejaDup last-backup "'2020-07-08T17:16:03.270477Z'"
gsettings set org.gnome.DejaDup allow-metered "false"
gsettings set org.gnome.DejaDup delete-after "0"
gsettings set org.gnome.DejaDup.Remote folder "'BackupVM'"
